'use client'

import { CacheProvider } from "@chakra-ui/next-js"
import { ChakraProvider,extendTheme } from "@chakra-ui/react"


// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }
const theme = extendTheme({
  styles: {
    global: {
      body: {
        bg: "#1A202C", // Replace with your desired background color
      },
    },
  },
});
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CacheProvider>
        <ChakraProvider theme={theme}>
        {children}
        </ChakraProvider>
        </CacheProvider>
        </body>
    </html>
  )
}
