'use client'

import { CacheProvider } from "@chakra-ui/next-js"
import '@fontsource/roboto-condensed';
import { ChakraProvider,extendTheme } from "@chakra-ui/react"
import { Inter } from "@next/font/google";

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// const inter = Inter({ subsets: ["Roboto Condensed"], variable: "--font-inter" });
const theme = extendTheme({
  styles: {
    global: {
      body: {
        //bg: "#1A202C", // Replace with your desired background color
       bg:"black"
      },
      fonts:{
        body:`'Roboto Condensed',sans-serif`,
      }
    },
  },
 
});
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CacheProvider>
        <ChakraProvider theme={theme}>
        {children}
        </ChakraProvider>
        </CacheProvider>
        </body>
    </html>
  )
}
